kind: smusher
name: Smusher
description: Automatically compresses your jpeg and png image assets to save bandwidth and speed up your project
discovers: unoptimized image
active: true
checkout: patch
author:
  name: Tom Moor
  email: tom.moor@gmail.com
repository:
  type: git
  url: https://github.com/pushbit-behaviors/smusher
files:
  - !ruby/regexp '/.+\.jpe?g\z/i'
  - !ruby/regexp '/.+\.png\z/i'
triggers:
  - pull_request_opened
actions:
  - pull_request
keywords:
  - image
  - jpeg
  - photo
  - compression
  - optimization
